services:
  radio_flask:
    build:
      context: .
      dockerfile: Dockerfile.flask
    container_name: radio_flask
    image: ghcr.io/pmhalvor/radio_flask:alpha
    restart: always
    ports:
      - "8888:8888"
    volumes:
      - ./.token:/radio/.token
    env_file:
      - .env
    environment:
      DEBUG: "false"
    platform: linux/amd64

  # new_radio:
  #   build: 
  #     context: .
  #     dockerfile: Dockerfile.radio
  #   container_name: new_radio
  #   restart: always
  #   ports:
  #     - "5002:5002"
  #   env_file:
  #     - .env
  #   environment:
  #     DEBUG: "false"
  #   platform: linux/amd64