services:
  radio_streamlit:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    container_name: radio_streamlit
    image: ghcr.io/pmhalvor/radio_streamlit:${TAG}
    restart: always
    ports:
      - "8501:8501"
    volumes: # needs to be present to run 'docker compose up'
      - ./.token:/radio/.token
    env_file:
      - .env
    platform: linux/amd64
