services:
  radio_flask:
    build:
      context: .
      dockerfile: Dockerfile.flask
    container_name: radio_flask
    image: ghcr.io/pmhalvor/radio_flask:alpha
    restart: always
    ports:
      - "8888:8888"
    volumes:
      - ./.token:/radio/.token
    env_file:
      - .env
    environment:
      DEBUG: "false"
    platform: linux/amd64

  radio_streamlit:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    depends_on:
      - radio_flask
    container_name: radio_streamlit
    image: ghcr.io/pmhalvor/radio_streamlit:alpha
    restart: always
    ports:
      - "8501:8501"
    volumes:
      - ./.token:/radio/.token
    env_file:
      - .env
    environment:
      # Use the service name 'api-service' to reference the host of the API.
      API_HOST: "radio_flask"
      API_PORT: "8888"
    
    platform: linux/amd64